### PR TITLE
Remove deprecation warning, bump react-async-bootstrapper version

### PR DESCRIPTION
**Pull request by szist**
This should solve deprecation warnings when using react-jobs with the latest `react-async-bootstrapper`
```
"react-async-bootstrapper" deprecation notice: please rename your "asyncBootsrap" methods to "bootstrap"
```

### CODE REVIEW

**Comment by LeeCheneler** [comment]
Is this going to get merged??

**Comment by ctrlplusb** [comment]
Hey @LeeCheneler 

Sorry I haven't given all 3 projects any love of recent and need to do a refresh on them all.

I will try and see to the dependency updates within the next few days.

Regards;

**Comment by LeeCheneler** [comment]
Ah brilliant 😃 

FYI, these packages are totally awesome! Vastly simplify the whole SSR async problem!

**Comment by ctrlplusb** [comment]
Closing this as I have done it separately. Apologies - I wanted to do a big dep update and some refactoring at the same time. 

Thanks for your help and patience! ⭐️

**Pull request closed without merging**
