### PR TITLE
Adding redux related areas to the README todo

### PR DESCRIPTION
**Pull request by oyeanuj**
Hi @ctrlplusb, this is looking promising!

I've added a section in the comparison that might be relevant to a user using redux more heavily, as well as made the recipe title more generic so that any Redux user would click on it.

Hope this is relevant!

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Thanks!

Yeah, I agree that we should make it a bit more generic. We need to come up with some ideas to fill it up too.  Are you using `redux-thunk`?

**Comment by oyeanuj** [comment]
@ctrlplusb Sorry, didn't get the notification. I am using something very close to redux-thunk, but based off the original boilerplate I started off. 

Here is that code: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js

I use a slightly modified version of the above.

**Comment by ctrlplusb** [comment]
Hey @oyeanuj I may look to create a `redux-jobs` abstraction on top of this library to make the resultant API a bit more friendly to a redux environment (i.e. less boilerplate).

I am going to close this for now. :)

**Comment by oyeanuj** [comment]
@ctrlplusb Sounds good! Please do post an update here when you do 😄

**Comment by oyeanuj** [comment]
@ctrlplusb Just checking back in.. did you ever end up creating a `redux-jobs` abstraction as a library or a gist?

**Pull request closed without merging**
